/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'status' : OrderStatus,
  'createdAt' : bigint,
  'totalCents' : bigint,
  'orderId' : OrderId,
  'shippingAddress' : ShippingAddress,
  'buyer' : Principal,
  'items' : Array<OrderItem>,
}
export type OrderId = number;
export interface OrderItem {
  'color' : string,
  'size' : string,
  'productId' : ProductId,
  'quantity' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'placed' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Product {
  'title' : string,
  'imageBlob' : Uint8Array,
  'description' : string,
  'productId' : ProductId,
  'sizes' : Array<string>,
  'colors' : Array<string>,
  'priceCents' : bigint,
}
export type ProductId = number;
export interface ShippingAddress {
  'zip' : string,
  'city' : string,
  'fullName' : string,
  'addressLine1' : string,
  'addressLine2' : [] | [string],
  'phone' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[Array<OrderItem>, ShippingAddress], Order>,
  'createProduct' : ActorMethod<
    [string, string, bigint, Array<string>, Array<string>, Uint8Array],
    Product
  >,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [
      ProductId,
      string,
      string,
      bigint,
      Array<string>,
      Array<string>,
      Uint8Array,
    ],
    Product
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];